<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyVersion>1.1.0.0</AssemblyVersion>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.11" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.11" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\hdhr-api\Com.ZachDeibert.MediaTools.Hdhr.Api.csproj" />
    </ItemGroup>
</Project>
